require("ganesh.lazy_nvim")
require("ganesh.core.options")
require("ganesh.core.autocmds")
require("ganesh.core.keymaps")
require("ganesh.core.colorscheme")
require("ganesh.plugins.smartcolumn")
require("ganesh.plugins.comment")
require("ganesh.plugins.easy-escape")
require("ganesh.plugins.nvim-tree")
-- require("ganesh.plugins.neo-tree")
require("ganesh.plugins.lualine")
require("ganesh.plugins.nvim-cursorline")
require("ganesh.plugins.telescope")
require("ganesh.plugins.toggleterm")
-- require("ganesh.plugins.session_manager")
require("ganesh.plugins.neoclip")
-- require("ganesh.plugins.lightspeed")
require("ganesh.plugins.nvim-cmp")
require("ganesh.plugins.luasnip")
require("ganesh.plugins.lsp.mason")
require("ganesh.plugins.lsp.lspsaga")
require("ganesh.plugins.lsp.lspconfig")
require("ganesh.plugins.lsp.null-ls")
-- require("ganesh.plugins.surround")
require("ganesh.plugins.indent")
require("ganesh.plugins.lsp.fidget")
require("ganesh.plugins.autopairs")
require("ganesh.plugins.treesitter")
require("ganesh.plugins.gitsigns")
require("ganesh.plugins.dashboard.alpha")
require("ganesh.plugins.bookmarks")
require("ganesh.plugins.code-run")
require("ganesh.plugins.wilder")
require("ganesh.plugins.flutter")
require("ganesh.plugins.dap")
require("ganesh.plugins.chatgpt")
require("ganesh.plugins.zenmode")
-- require("ganesh.plugins.twilight")
require("ganesh.plugins.ccc")
require("ganesh.plugins.silicon")
require("ganesh.plugins.browse")
require("ganesh.plugins.auto-session")
