# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="cloud"
# ZSH_THEME="spaceship"

# Set list of themes to pick from when loading at random
# Setting this variable when ZSH_THEME=random will cause zsh to load
# a theme from this variable instead of looking in $ZSH/themes/
# If set to an empty array, this variable will have no effect.
# ZSH_THEME_RANDOM_CANDIDATES=( "robbyrussell" "agnoster" )

# Uncomment the following line to use case-sensitive completion.
# CASE_SENSITIVE="true"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment one of the following lines to change the auto-update behavior
# zstyle ':omz:update' mode disabled  # disable automatic updates
# zstyle ':omz:update' mode auto      # update automatically without asking
# zstyle ':omz:update' mode reminder  # just remind me to update when it's time

# Uncomment the following line to change how often to auto-update (in days).
# zstyle ':omz:update' frequency 13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS="true"

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
# DISABLE_AUTO_TITLE="true"

# Uncomment the following line to enable command auto-correction.
# ENABLE_CORRECTION="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# You can also set it to another string to have that shown instead of the default red dots.
# e.g. COMPLETION_WAITING_DOTS="%F{yellow}waiting...%f"
# Caution: this setting can cause issues with multiline prompts in zsh < 5.7.1 (see #5765)
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

# Which plugins would you like to load?
# Standard plugins can be found in $ZSH/plugins/
# Custom plugins may be added to $ZSH_CUSTOM/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git 
zsh-autosuggestions 
zsh-syntax-highlighting 
web-search
)

source $ZSH/oh-my-zsh.sh

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.

# export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
export JAVA_HOME="/usr/lib/jvm/java-11-openjdk-amd64"
export PATH="$PATH:$JAVA_HOME/bin"
export PATH="$PATH:/root/flutter/bin"
export PATH="$PATH:/usr/lib/dart/bin"

# Example aliases
# alias ohmyzsh="nv ~/.oh-my-zsh"

# alias from external source
source $HOME/.zsh_aliases

# # Git

# alias gt='git'
# alias 1tree='git log --all --decorate --oneline --graph'
# alias 2tree='git log --all --decorate --graph'
# # alias fch='tufetch'

# alias ggs="git status"
# alias ggch="git checkout"
# alias ggpc="git push origin $(git branch 2>/dev/null | grep '^*' | colrm 1 2)"
# alias gta="git add -A"
# alias gtps="git push origin"
# alias gtpl="git pull origin"
# alias gtc="git commit -am"

# #https://unix.stackexchange.com/questions/3773/how-to-pass-parameters-to-an-alias
# # https://stackoverflow.com/questions/1583219/how-can-i-do-a-recursive-find-replace-of-a-string-with-awk-or-sed
# # alias replace='tmp_f(){ grep -rl ${1} . | xargs sed -i s/${1}/${2}/g; unset -f tmp_f; }; tmp_f'


# alias ggremote="git remote -v"  # check all remotes
# alias ggbranch="git branch -v"  # check all branches

# # essentials
# alias e='nv' # edit
# alias f='exa -l -a --icons --sort=size --colour=auto --time-style=long-iso -F' # ls
# alias fl='exa -F'
# alias cc='xclip -selection clipboard' #copy to clipboard
# alias v='xclip -o' #paste
# alias d='clear'
# alias q="exit"
# alias pls="sudo"
# alias cw="pwd | cc"

#-------------------=== Neofetch ===-------------------------------
# alias nfetch='neofetch --ascii --source $HOME/.config/neofetch/logos/arch_ascii.txt'

#-------------------=== Utilities ===-------------------------------

# General

# alias ctrm='update-alternatives --config x-terminal-emulator'
# alias gksu='pkexec env DISPLAY=$DISPLAY XAUTHORITY=$XAUTHORITY DBUS_SESSION_BUS_ADDRESS=$DBUS_SESSION_BUS_ADDRESS'
# alias gksudo='gksu'
# alias sctrm='sudo update-alternatives --config x-terminal-emulator'
# alias dtct_key="xev -event keyboard"
# alias get_gtk='gsettings get org.gnome.desktop.interface gtk-theme'
# alias eco='echo'
# alias rm_crash='echo -e "\nThe following crashes were found and will now be removed:"; ls -l /var/crash/; sleep 1; sudo rm /var/crash/* && echo -e "\nMessage (OK): Succesfully cleared crashes!\nExit Status: $?" || echo -e "\nMessage (FAILED): Nothing removed"'

# changing cursor shape

# alias line='echo -e "\033[5 q"'         #blinking pipe bar
# alias nbline='echo -e "\033[6 q"'       #not blinking pipe bar
# alias block='echo -e "\033[1 q"'        #blinking block
# alias nbblock='echo -e "\033[2 q"'      #not blinking block
# alias uscore='echo -e "\033[3 q"'       #blinking underscore
# alias nbuscore='echo -e "\033[4 q"'     #not blinking underscore

#-------------------=== nums info ===-------------------------------
# 1 is the blinky block cursor
# 2 is the default (non-blinky) block cursor
# 3 is blinky underscore
# 4 fixed underscore
# 5 pipe bar (blinking)
# 6 fixed pipe bar


# langs
alias pthn="python3.8"
alias goi="go mod init test"
alias cjava='update-alternatives --config java' #change java version
alias scjava='sudo update-alternatives --config java' #change java version
alias gp="g++"
alias pg="g++"

#-------------------=== aliases ===-------------------------------
#terminal aliases
#change default terminal

#-------------------=== cd(s) ===-------------------------------
# alias ..="cd .."
# alias ...="cd ../.."
# alias ....="cd ../../.."
# alias .....="cd ../../../.."
# alias ......="cd ../../../../.."
# alias .......="cd ../../../../../.."
# alias ........="cd ../../../../../../.."

#date formats
alias sdate='date +"%d-%m-%y"'


# alias 1getip="ip route get 1.2.3.4 | awk '{print $7}'"
# alias 2getip="hostname -I | awk '{print $1}'"
# alias vom="vim"
# alias co="cd out/; lh; cd .."
# alias hl="lh"
# alias pww="pwd"
# alias getfm="cat /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy"
# alias getfanmode="cat /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy"
# alias gfm="cat /sys/devices/platform/asus-nb-wmi/throttle_thermal_policy"

# fan modes:
#    + 2 = silent
#    + 0 = balance
#    + 1 = turbo
# And some for commonly used variations of ls (and typos):
# alias ll="ls -l"
# alias lo="ls -o"
# alias lh="ls -lha"
# alias la="ls -la"
# alias sl="ls"
# alias l='ls -CF'
# alias s="ls"

# This is GOLD for finding out what is taking so much space on your drives!
# alias diskspace="du -S | sort -n -r |more"

# Command line mplayer movie watching for the win.
#alias mp="mplayer -fs"

# Show me the size (sorted) of only the folders in this directory
# alias dicts="find . -maxdepth 1 -type d -print | xargs du -sk | sort -rn"

# =============================================================================
# Terminal General
# =============================================================================
# alias so='source'
# # alias thisd='xdg-open .'    # open current directory in file explorer
# alias tuf_info='sudo dmidecode | grep "BIOS Inf\|Board Inf" -A 3'
# alias grep='grep --color=auto'
# alias fgrep='fgrep --color=auto'
# alias egrep='egrep --color=auto'
# alias tmp="cd /tmp"

# Add an "alert" alias for long running commands.  Use like so:
#   sleep 10; alert
# alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
# alias alert='notify-send --urgency=normal "finished execution ($?)" "$(history 1 | tail -2 | head -1 | cut -c8-999)"'

# =============================================================================
# VIEWING & EDITING FILES
# =============================================================================

#-------------------=== rust-bat ===-------------------------------
# alias bca='batcat'

#-------------------=== Terminal Editors ===-------------------------------
# alias nv='/usr/local/bin/nvim.appimage'
# alias test_echo='echo $@ > test.txt'
#
#
# #-------------------=== w/ Vim ===-------------------------------
#
# # install with:
# # sudo snap install --edge nvim --classic
# alias ef_systemd='sudo vim /etc/systemd/system.conf'
# alias ef_kitty='vim ~/.config/kitty/kitty.conf'
# alias ef_bash='vim ~/.bashrc'
# alias ef_vim='vim ~/.vimrc'
# alias ef_nvim='vim ~/.config/nvim/init.vim'
# alias ef_ss='vim ~/.config/starship.toml'
# alias ef_sa='vim ~/.shell_aliases'
#
# #-------------------=== w/ Nvim ===-------------------------------
#
# alias efn_systemd='sudo nvim /etc/systemd/system.conf'
# alias efn_kitty='nvim ~/.config/kitty/kitty.conf'
# alias efn_sh='nvim ~/.bashrc'
# alias efn_vim='nvim ~/.vimrc'
# alias efn_nv='nvim ~/.config/nvim/init.lua'
# alias efn_sa='nvim ~/.shell_aliases'
# alias efn_tm='nvim ~/.tmux.conf'
# alias efn_ala='nvim ~/.config/alacritty/alacritty.yml'
# alias efn_sa='nvim ~/.shell_aliases'
# # alias efn_ss='nvim ~/.config/starship.toml'
#
# #-------------------=== Cat-ting ===-------------------------------
# alias ct_bash="cat ~/.bashrc"
# alias ct_vim="cat ~/.vimrc"
# alias ct_kitty="cat ~/.config/kitty/kitty.conf"
# alias ct_nvim='cat ~/.config/kitty/kitty.conf'
